# Generated by Django 4.2.7 on 2023-12-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='dirección Empresa'),
        ),
    ]
